### ISSUE TITLE
Program Name

### ISSUE THREAD

**Issue by smaragdus** [setvisible/arrow-dl#46]
As it was discussed in another issue (#43) perhaps the name of the program- **DownZemAll!**, is not very unique.

I case the developer chooses to rename the project I will suggest several possible new names:

- **Down Right Now**
- **Get All**
- **Get Fast**
- **Get Quick**
- **Get Swift**
- **Brisk Downloader**
- **Deft Downloader**
- **Fast Downloader**
- **Lightning Downloader**
- **Liquid Downloader**
- **Nimble Downloader**
- **Prompt Downloader**
- **Quick Downloader**
- **Smart Downloader**
- **Swift Downloader**
- **Thunder Downloader**
- **Thunderbolt Downloader**

**Down Right Now** may look the obvious candidate since thus the project and the browser extensions will have the same name.

There might be better names of course.

This should be thought over very carefully since renaming a project (especially a well-established one) is a pain.

**Comment by setvisible** [comment]
QuickDL
FastDL
Speedl = speed + DL
Express DL
Pipedownload
Stuff2download
Download it
Alldownload
Downloadeverypiece

**Comment by setvisible** [comment]
Hi,

Proud to publish the new project's name : 

- **"arrow-dl"**
- **aka Arrow-DL, aka Arrow Downloader**

Because the icon is an arrow, and because www.arrow-dl.com was available

Regards
